debug: false
log_file_path: data-tools.log
db_path: data.db
zap_data_path: "ZAP"
batch_size: 1000
max_concurrent_file_operations: 10

file_names_to_ignore:
  - .DS_Store
  - Thumbs.db

folder_names_to_ignore:
  - "@eaDir"                # Synology
  - .@__thumb               # QNAP
  - .Trashes                # macOS
  - .TemporaryItems         # macOS
  - .DocumentRevisions-V100 # macOS
  - .Spotlight-V100         # macOS
  - .fseventsd              # macOS
#  - .stversions             # Syncthing