debug: false
db_path: test.db
log_file_path: data-tools.log
batch_size: 1000
max_concurrent_file_operations: 10

file_names_to_ignore:
  - .DS_Store

folder_names_to_ignore:
  - "@eaDir"
  - .Trashes
  - .TemporaryItems
  - .DocumentRevisions-V100
  - .Spotlight-V100
#  - .stversions